### ISSUE TITLE
Serialization Bug 

### ISSUE THREAD

**Issue by oconn** [Lokeh/punk2#4]
It appears that there may be some errors being swallowed when it comes to serialization.

```clojure
cljs.user> (tap> [:test 1])
true
cljs.user> (tap> [:test (fn [a] a)])
true
cljs.user> (tap> [:test 2])
true
```

results in only `[:test 1]` being displayed in punk2

**Comment by Lokeh** [comment]
Ah hm. Does it totally break after tapping the function? E.g. no other taps persist?

I think that I need to set it up so that it will handle arbitrary reader literals, since I think functions get serialized as `#object ...`, which shouldn't be too hard.

If it's also breaking completely after encountering that error, I should fix the error handling as well.

**Comment by oconn** [comment]
Yeah that appears to be the behavior (No further logs are persisted).

**Comment by sogaiu** [comment]
@Lokeh 

Any further thoughts on:

> I think that I need to set it up so that it will handle arbitrary reader literals, since I think functions get serialized as `#object ...`, which shouldn't be too hard.

?

**Comment by Lokeh** [comment]
This was fixed by https://github.com/Lokeh/punk2/commit/b924f2d95ee78c1d944da76a4a1e960b52693846
